# Generated by Django 2.1.1 on 2018-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('votes_total', models.IntegerField(default=1)),
                ('body', models.TextField()),
                ('amazon_link', models.TextField()),
            ],
        ),
    ]
