# Generated by Django 2.1.1 on 2018-09-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180919_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='tagged',
            field=models.CharField(default='book', max_length=40),
        ),
    ]
